//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden üretildiğinde kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspx_web_tasarim_ve_programlama_ders_notlari._16._4._19
{


    public partial class _default
    {

        /// <summary>
        /// form1 denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
